pathman/releases.js

Originally `pathman` was only for `amd64`.
This remained true on Windows 10 and OS X, but changed for Linux. This fixes that.

hotfix for amd64 misclassification

---

vps-utils/cap-net-bind.sh

Fixes whitespace bug that caused syntax error.

whitespace bugfix for bash command

---

.gitignore
_common/github.js
_webi/template.sh
package-lock.json
package.json

- (emergency) Github Release API rate limits hit at 60/hr. Add authentication for 5,000/hr
- (high priority) All Mac/Linux binaries were being installed with a trailing `}` in their name

Hotfixes that requiring cowboy deploy to production

---

prettier/README.md

Addressing issue #69
Closest flag to this is the --ignore-path option in the Prettier docs, but it's different (path to a list of ignored directories). Doesn't seem necessary to include here as it already looks for the ./.prettierignore file

correct Prettier cheat sheet about `--ignore`

---

_npm/README.md
_npm/package-lock.json
_npm/package.json
_webi/template.sh
comrak/README.md
comrak/install.ps1
comrak/install.sh
comrak/releases.js

Re: #75 
Had to dig a bit into a lot of nuance detail in regards to both safely escaped HTML + CSP and raw unsafe HTML + scripts.
Also accidentally included the `_npm` updates. Just as well to merge those now too.
Live at https://beta.webinstall.dev/comrak
```bash
export WEBI_HOST=https://beta.webinstall.dev
curl -fsS https://webinstall.dev/comrak | bash
```
I still want to add this to the homepage too.

Add comrak for Markdown to HTML

---

_webi/template.sh

`spctl` requires a `sudo` / Admin prompt, which will ALWAYS trigger on High Sierra and sometimes trigger on Catalina.
By trying xattr first, we can avoid the admin prompt.
Without being an apple guru it's difficult to tell if this will work as expected, but I've tested it as best I can.
Tested with a fresh Catalina VM. All is well there, so I must assume all is well, period.

remove xattr com.apple.quarantine before trying spctl

---

.gitignore

As in the issue #96 it was mentioned to add the required patterns to the `.gitignore` file I have did that and also as `install-*.sh` was already present there was no required to add that pattern.

Fix #96: Added required files to the readme.

---

rg/README.md

The commit messages provide a tiny bit more detail, but basically:
1. The "rip" in "ripgrep" means "to rip through text" and not "kill grep" or "grep is dead."
2. Dial back some embellishment about ripgrep's performance.
Disclaimer: I'm the author of ripgrep.
Thanks!

rg: tweak the wording in the ripgrep description

---

_webi/template.sh
brew/install.sh

Re: https://github.com/webinstall/webi-installers/issues/141
`brew` requires `git` and such. We can easily test for that before attempting to install (and we may want to copy that over to anything that needs git).
We're switching from
```bash
{
dostuff ...
}
```
to
```bash
function __dostuff() {
dostuff ...
}
__dostuff()
```
Originally I introduced the grouping because it will cause an error if a script is not completely downloaded before it is run. However, it introduced some bad expansions in certain cases.
Using a function has the same benefits, but no known downsides (yet).

fix brew on clean macos, remove group expansion

---

k9s/README.md
k9s/install.ps1
k9s/install.sh
k9s/releases.js

This is with reference to issue #170. I have created the install scripts and tested if the installation works. It worked without any errors on my system (Ubuntu 20.04). 
Added required preflight checks according to K9s documentation and some common command-line parameter options in the cheat sheet section. 
Adjusted `pkg_get_current_version` to work with the k9s version output.

Added k9s installer

---

_webi/template.sh

One of the conditionals was accidentally inverted in the last commit and I didn't notice because I was installing things I had already installed.
This fixes that.

bugfix: invert download check

---

nerdfont/install.ps1

New line causes the command to throw an exception instead of correctly installing font

Fix breaking newline

---

vim-nerdtree/nerdtree.vim

Ignore dirs with those names, not anything that starts with those strings.

vim-nerdtree config ignores anything that starts with .git node_modules dist etc

---

gprox/install.sh

This is just removing the `pkg_install` method and using the default, which seems to work. Fixes #264

Use the default webi_install method for gprox

---

_webi/template.sh
fish/install.sh
gh/README.md
gh/install.ps1
gh/install.sh
gh/releases.js
git-gpg-init/README.md
git-gpg-init/git-gpg-init.sh
git-gpg-init/install.sh
gnupg/install.sh
gpg-pubkey/README.md
gpg-pubkey/gpg-pubkey-id.ps1
gpg-pubkey/gpg-pubkey-id.sh
gpg-pubkey/gpg-pubkey.ps1
gpg-pubkey/gpg-pubkey.sh
gpg-pubkey/install.ps1
gpg-pubkey/install.sh
gpg/README.md
gpg/install.ps1
gpg/install.sh
gpg/releases.js
iterm2/install.sh
macos/releases.js
ssh-pubkey/install.sh
ssh-utils/ssh-adduser.sh
ssh-utils/ssh-pubkey.sh

This is not a security bug, but an additional security measure.
UsePAM is usually not turned on for Linux servers, but is often turned on for macOS.
This is more for completeness than the typical Linux use case.
Re: https://apple.stackexchange.com/questions/315881/disable-ssh-password-authentication-on-high-sierra/340006?noredirect=1#comment616104_340006

security: also check for UsePAM

---

_example/install.sh
_webi/template.sh

This change removes the need for specialized version checks and should make switching between versions and installing webi versions that are intended to take precedence over local versions all more reliable.
Now, rather than checking the output of `pkg_get_current_version`, we just check that the source and destination files are either the same, or different, and do _The Right Thing™_ accordingly.
I think the changes have been fairly well tested.
Just rm -rf ~/.local/bin/{rg,sd,fd} ~/.local/opt/{rg,sd,fd,node,go}* and reinstall some stuff and see that it all works as expected.
For reference, this is the code we removed:
```bash
pkg_current_version=""
if [ -n "$(command -v pkg_get_current_version)" ]; then
pkg_current_version="$(
pkg_get_current_version 2> /dev/null |
head -n 1
)"
fi …
```

refactor: replace pkg_get_current_version with file check

---

_webi/normalize.js
gh/README.md
package.json
test/README.md

- `linux-musl` should be higher sort order (preferred) than `linux-gnu`
- `arm64` can be given instead of `armv7l` (for RPi 3+ Raspbian)
- `armv7l` can be given instead of `arm64` (for RPi 3+ Ubuntu  + _Bionic_)

bugfix(linux): prefer musl builds + allow armv7l or arm64 for RPi

---

jshint/jshintrc.webi.json5

Changed to: sed -e 's://.*::g' ~/.jshintrc.webi.json5 > .jshintrc

Updated typo for run command

---

gh/README.md

Adds the following items to a new section called Actions:
- listing action workflows
- viewing the pass/fail steps of a workflow by ID
- rerun a workflow

add a few Github Actions entries to the cheat sheet

---

_webi/template.ps1

#350 
I think this is a good place to put this check. Tested it and it throws a nice ugly error when you try to run the install-whatever.ps1 with powershell as admin and works in a non-elevated environment.

fix(webi): add check for windows pwsh being run as admin

---

koji/README.md
koji/install.sh
koji/releases.js
test/install.sh

Not a clue what the requirements are for getting a package added, but would be nice to get my little conventional commit util in here if possible. No windows support atm, so no installer for it.
The project for reference: https://github.com/its-danny/koji

feat(koji): add koji

---

_webi/bootstrap.ps1

This fixes bug whereby one could only run webi from the home directory because it created the `.local\bin` in whatever directory it was run.

Run bootstrap.ps1 from any directory

---

_webi/bootstrap.sh
_webi/webi-pwsh.ps1

This commit adds usage/help information to the webi installer in 3 scenarios.
1. if no command is provided _Eg. `webi`_
2. if `-h` is appended _Eg. `webi -h`_
3. or if `--help` is appended _Eg. `webi --help`_

Add help command usage

---

README.md
_npm/README.md
bat/README.md
caddy/README.md
dotenv-linter/README.md
pathman/README.md
powershell/README.md
webi/README.md
wsl/install.sh
wsl1/install.sh
wsl2/README.md
wsl2/install.sh

This pull request removes mentioning of Windows version. Some of them are only referring to the platform, not caring about the version, and the rest shouldn't need to either. webi packages are categorized for developers and few developers are using Windows version that old.  <sub>Remember, Windows 10 came out in July _2015_, when io.js was still around and Alphabet Inc. doesn't exist.</sub>
This also helps in case people are searching for "Windows 11", despite it being just a glorified version of Windows 10.

Drop unnecessary mentions of Windows version

---

postgres/README.md

Added instructions for secure remote connections
- enable tls/ssl
- add user with password
- allow user for remote connections
- test connection

postgres(cheatsheet): add secure remote user instructions

---

vim-go/README.md
vim-go/install.sh

Go 1.18 dropped support for `go get` so as suggested, I have replaced `go get` with `go install`. Please go through it and let me know if any change is required.

[Bug] vim-go: Go 1.18 drops support for go get  #441

---

go-essentials/README.md
go-essentials/install.ps1
go-essentials/install.sh
golang/install.ps1
golang/install.sh

Due to complications with version changes between go 1.16 and go 1.18 I think it's best to remove the non-required go tooling from the `go` package and install it instead with `go-essentials`.
This provides a path forward to that with notification of upcoming breaking change.

add go-essentials, migrate go tooling from go

---

README.md
_webi/bootstrap.sh
_webi/template.sh

Prior instructions gave this new coder the impression that further changes to PATH were required after the completion of the Webi script (e.g. with Golang):
```console
Installed 'go v1.18.0' to ~/.local/opt/go
Installed go "x" tools to GOBIN=$HOME/go/bin
You need to update your PATH to use golang:
export PATH="/home/db/go/bin:$PATH"
export PATH="/home/db/.local/opt/go/bin:$PATH"
```
```console
Installed 'go v1.18.0' to ~/.local/opt/go
Installed go "x" tools to GOBIN=$HOME/go/bin
PATH.env updated with:
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.local/opt/go/bin:$PATH"
IMPORTANT: To use golang, copy, paste, and run this command to update your current PATH:
source ~/.config/envman/PATH.env
(opening a new shell will have the same effect)
```
Revised to clarify the actual actions …

Webi post install instructions update

---

_webi/releases.js

the rest of the solution for https://github.com/webinstall/webi-installers/issues/396

fix: make 'pkg@' just 'pkg' when missing version

---

bat/install.sh
chromedriver/install.sh
comrak/install.sh
curlie/install.sh
dotenv-linter/install.sh
fd/install.sh
ffmpeg/install.sh
fzf/install.sh
gh/install.sh
goreleaser/install.sh
hexyl/install.sh
jq/install.sh
k9s/install.sh
lsd/install.sh
mutagen/install.sh
pandoc/install.sh
pathman/install.sh
rg/install.sh
sass/install.sh
sd/install.sh
shellcheck/install.sh
shfmt/install.sh
watchexec/install.sh
xz/install.sh

List of the packages which I remove the echo command:  
```bash
yorune@MacBook ~/git/webi-installers main $ grep -iEr 'echo *\$\(' | awk -F: '{print $1}' | sed '/curlie/d'
./sd/install.sh
./comrak/install.sh
./ffmpeg/install.sh
./pandoc/install.sh
./gh/install.sh
./dotenv-linter/install.sh
./mutagen/install.sh
./fd/install.sh
./rg/install.sh
./lsd/install.sh
./xz/install.sh
./shfmt/install.sh
./goreleaser/install.sh
./pathman/install.sh
./hexyl/install.sh
./shellcheck/install.sh
./k9s/install.sh
./bat/install.sh
./chromedriver/install.sh
./jq/install.sh
./sass/install.sh
./watchexec/install.sh
./fzf/install.sh
```
  
  I tested the changed packages in the dev env in the docker container.

Remove echo from the all repo

---

_webi/bootstrap.sh
_webi/template.sh

- use `case` for `== *i*`
- use `grep` for `=~`

fix #478: convert complex 'if' bashisms

---

_webi/template.sh

somehow this got left out or dropped from the commit that should have fixed it

hotfix(posix): double quote vars that require it

---

CONTRIBUTING.md
README.md
_npm/README.md
_npm/scripts/install-webi.js
_webi/bootstrap.ps1
_webi/bootstrap.sh
_webi/releases.js
goreleaser/README.md
gpg-pubkey/README.md
powershell/README.md
pyenv/README.md
python/install.sh
python2/install.sh
ssh-pubkey/README.md
webi/README.md

We now have the domain `webi.sh` for Posix Scripts and `webi.ms` for Microsoft PowerShell.
This update various documentation to use the new domains.
This won't go live yet, but it's ready for approval.

docs: add new webi.sh and webi.ms

---

_webi/frontmarker.js
_webi/packages.js
package-lock.json
package.json

This removes the dead frontmatter-in-bash (shmatter/yash) that we stopped using a while ago.
It also updates `marked` to v4 due to `npm audit` complaints about potential RegEx DoS. We're not affected (the cheat sheets are trusted and static), but it's a small change and eliminates the warning.

ref!: remove 'shmatter' and update 'marked'

---

_webi/releases.js
_webi/serve-installer.js
_webi/transform-releases.js

Re: https://github.com/webinstall/webi-installers/issues/534
I want to get to process-level isolation, but looking over this I'm not convinced that that would do any better with just that change - something is going wrong with failed network requests.
This will do a better job at not hard failing.
There may have been a promise deadlock (those are difficult to mentally model, so I can't say for sure), but this removes the conditions that I thought were suspect.

fix: better fallbacks for release info updates

---

_webi/releases.js
_webi/serve-installer.js
_webi/transform-releases.js

In the latest update - which thankfully _didn't_ restart production when it deployed - installers with no `releases.js` all failed to install.
This fixes that.

hotfix: allow installers without releases

---

_webi/bootstrap.sh
_webi/template.sh
_webi/ua-detect.js
brew/install.sh
fish/install.sh
git/install.sh
gpg/install.sh

fixes #561, and possibly an old issue with 32-bit vs 64-bit OS on 64-bit Raspberry Pi - we hope :)
| Flag | Meaning | Example |
| ----- | --------------- | -------------------- |
| `-s` | `operating system implementation` | `Darwin` |
| `-r` | `operating system release level` | `22.2.0` <br> (i.e. of Darwin) |
| `-v` | `operating system release version` | `#89-Ubuntu SMP PREEMPT Mon Dec 5 08:38:35 UTC 2022` |
| `-m` | `machine platform` | `arm64` |
| `-p` | *non-standard* <br> `machine processor architecture` | `arm` |
```sh
uname -srm
```
```text
Darwin 22.2.0 arm64
Linux 5.15.0-50-generic x86_64
Linux 5.4.0-1078-raspi aarch64
Linux 5.15.32-v7l+ armv7l
```
```sh
uname -v
```
```text
Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 …
```

fix: replace 'uname -a' with 'uname -srm' for OS/Arch detection

---

_common/github.js
_webi/transform-releases.js

- fixed `staleAge = 5 * 60 * 1000` (had left out the 60 for local debug last time)
- always respond when usable data is available
- light readability update around fresh/stale/expired cache times

hotfix: another fix for github releases error responses

---

iterm2/README.md
iterm2/install.sh
node/README.md
postgres/install.sh

Installing to `~/Applications` is supported, but there are annoying caveats.
Since `/Applications` doesn't actually require `sudo` or have any of the issues, it was a bad idea to experiment with `~/Applications`. Shouldn't have done it.
Also, the `pgAdmin 4.app` package has a bad link (it should go two parents up, not one). Fixed that too.

hotfix: fix iTerm2.app install location and pgAdmin 4.app

---

bat/README.md
bat/install.sh
curlie/README.md
lsd/README.md
rg/README.md
rg/install.sh

Added Files section for ripgrep. 
I added the referenced config file from ripgrep's [docs](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file). I don't believe Webi is creating it and honestly, I didn't even know you could have a config file for ripgrep.

doc(rg) add Files section

---

vim-essentials/install.sh

Some people have node that was installed via `apt` which, of course, doesn't work for anything. \
(thanks Ubuntu...)
So we make `prettier` last.
We should probably have some sort of check in the `jshint` and `prettier` installers so that they don't succeed if node is in a system location.

fix(vim-essentials): install bins last in case they fail (looking at you sudo'd npm)

---

vim-prettier/prettier.vim
vim-shfmt/shfmt.vim

It looks like the desired behavior now exists upstream, so we can remove our special edits.
~/.vim/pack/plugins/start/vim-shfmt/plugin/shfmt.vim
```vim
" ...
autocmd BufWritePre *.sh Shfmt
autocmd FileType sh autocmd BufWritePre <buffer> Shfmt
" ...
```

fix: remove outdated config on formatters, and detect by file type

---

dashcore-utils/dash.example.conf
dashd/README.md

Many of the most important RPCs can't work without indexing turned on.
This will likely increase the system requirements as well.

fix(dashd): turn on indexes

---

vim-ale/ale.vim

A lot of headless images have the locale set to "C" by default. So much so that it makes sense to use ASCII rather than UTF8 for the vim-ale error icon.
```vim
- let g:ale_sign_error = '✘'
- let g:ale_sign_warning = '⚠️'
+ let g:ale_sign_error = 'x'
+ let g:ale_sign_warning = '!'
```
```text
Error detected while processing function <SNR>82_VimCloseCallback[11]..<SNR>82_VimExitCallback[22]..function <SN
R>82_VimCloseCallback[11]..<SNR>82_VimExitCallback[15]..<lambda>13[1]..<SNR>77_ExitCallback[28]..<SNR>76_HandleE
xit[30]..ale#engine#HandleLoclist[40]..ale#engine#SetResults:
line   10:
E117: Unknown function: ale#sign#SetSigns
Error detected while processing function <SNR>82_VimCloseCallback:
line   11:
E171: Missing :endif
:
Error detected while processing function …
```

fix(vim-ale): use ascii rather than utf8

---

_webi/bootstrap.sh
_webi/normalize.js
_webi/serve-installer.js
_webi/template.sh
_webi/transform-releases.js
_webi/ua-detect.js
node/releases.js

Official node cannot run on `apline`
`musl` node cannot run on `ubuntu`.
We will need to add some sort of detection mechanism to determine whether or not musl is the default libc.
This may do the trick:
```sh
ldd /bin/ls | grep 'musl'
```

ref!(node): enable musl builds

---

ffmpeg/README.md

Add note about loss of DNS resolution due to statically linked `glibc`  and example scenario

doc(ffmpeg): Add DNS resolution note and example

---

dashcore-utils/dash.example.conf
dashd/README.md

1. as a workaround for inaccurate results from the `getaddressutxos` RPC it will be necessary to have `zmqpubhashchainlock` enabled so that `zmqpubrawtxlock` can be used to get the missing utxos and know when to expel them from memory.
2. update README with QuickStart

ref(dashcore-utils): add `zmqpubhashchainlock` to dash.example.conf

---

msvc-runtime
msvcruntime
vc-redist
vc-runtime
vc_redist
vcredist
vcruntime/README.md
vcruntime/install.ps1
vcruntime/install.sh
vcruntime140

Many of the Windows programs are compiled with MSVC, which requires the 25mb of Windows that Microsoft just won't install for you.
This makes that simpler.

Add MSVC Runtime (VC Redist) (vcruntime140.dll)

---

vim-ale/ale.vim

Very simple output change
```text
[jshint] : 'await' is not defined. [E]
```
```text
[shellcheck] SC2154: my_var is referenced but not assigned. [W]
```

fix(vim-ale): show linter and code in a way that works for jshint and shellcheck

---

sqlpkg/README.md
sqlpkg/install.ps1
sqlpkg/install.sh
sqlpkg/releases.js
test/install.sh

`sqlpkg` is a package manager for SQLite extensions. It currently supports ~62 extensions. The [command-line utility](https://github.com/nalgeon/sqlpkg-cli) provides easy access to the library of extensions, and handles installations across environments. The library of extensions can be explored here: https://sqlpkg.org/
I want to make it easy for applications and projects to add this utility so that they can then easily add SQLite extensions for their database.

feat(sqlpkg) Add sqlpkg CLI utility for installing SQLite extensions

---

atomicparsley/README.md

- artwork image manipulation is macOS-only
- ffmpeg 4.0+ can add artwork to mp4 files

atomicparsley: README.md corrections

---

ffuf/README.md
ffuf/install.ps1
ffuf/install.sh
ffuf/releases.js

added a security tool ffuf feroxbuster, it is commonly used by security researchers, I figured having an varied set of tools for webi would get more users in hope that translates to [Stars]

Add ffuf and feroxbuster (security based tooling)

---

dotenv-linter/README.md

Updated the Cheat Sheet for dotenv linter as according to https://github.com/webinstall/webi-installers/issues/251
I also changed --skip to shorthand -s which is less verbose but I kept compare verbose (I didn't do dotenv-lint c .env1 .env2)

docs(dotenv-linter): Update Cheat Sheet to be compatable with dotenv-linter v3.1

---

powershell/releases.js

`pwsh-7.4-preview` was showing up as stable.
This fixes that.

fix(pwsh): previews should be beta, not stable

---

gpg/install.sh
pyenv/README.md
pyenv/install.sh
python/README.md
python2/README.md
python3/README.md
rustlang/install.sh
webi/README.md

Re: https://github.com/webinstall/webi-installers/issues/697
these were missed last time (and broken)

fix+chore: replace leftover `pathman add`

---

cmake/install.sh

Re: #696
On macOS the `cmake` package as a hybrid `./opt/` / `.app` structure that we must account for:
```text
./
└── cmake-3.28.0-rc2-macos-universal/
└── CMake.app/
└── Contents/
├── _CodeSignature/
├── bin/
├── doc/
├── Frameworks/
│   ├── QtCore.framework/
│   ├── QtGui.framework/
│   ├── QtPrintSupport.framework/
│   └── QtWidgets.framework/
├── MacOS/
├── man/
├── PlugIns/
│   ├── platforms/
│   └── styles/
├── Resources/
└── share/
```

Fix: cmake on macOS (#696)

---

_common/github.js
_webi/normalize.js

Re: #696 (see comment about `-rc`)
The old default behavior was that if something was _NOT_ tagged as _prerelease_ then it was tagged as _stable_ (`cmake`, `powershell`, etc).
This new behavior will consider the name as well:
- if the release channel has NOT _already_ been tagged
- and the release matches similar to `(+.-_)(preview|beta|rc|alpha)(0-9)(+.-_)`
- tag it as `beta`
- otherwise tag it as `stable`
Since this merely delays the `beta` check until later, and no package names conflict with the pattern... hopefully nothing!
Just like some tools start out at version v0.0.1, it's possible we have **something that currently is _always_ beta** because no "stable" release has ever been made... I don't know what would happen in that case.
In releases with a **base64** tag, it's possible …

fix: better (lazier) 'stable' vs 'beta' detection

---

crabz/README.md
crabz/install.ps1
crabz/install.sh
crabz/releases.js

adding a rust tool called crabz

giving webi installer the gift of crabz

---

_common/github.js
_webi/bootstrap.sh
_webi/releases.js
_webi/template.sh
gh/README.md

Re: #698, #708 
Also:
```sh
webi --list
```
```text
[warn] the format of --list output may change
atomicparsley
awless
archiver
watchexec
zoxide
yq
```
```sh
webi --info ssh-pubkey
webi --info node
```
```text
'ssh-pubkey' is a special case that does not have releases
```
```json5
// Stable 'node' releases:
[
{
"name": "node-v20.9.0-aix-ppc64.tar.gz",
"version": "20.9.0",
"lts": true,
"channel": "stable",
"date": "2023-10-24",
"os": "aix",
"arch": "ppc64",
"ext": "tar.gz",
"download": "https://nodejs.org/download/release/v20.9.0/node-v20.9.0-aix-ppc64.tar.gz"
}
]
```

feat: add rudimentry --list and --info flags + minor cleanup

---

_webi/template.sh
git/install.sh
pyenv/install.sh
setcap-netbind/setcap-netbind.sh
sudo/install.sh
vim-beyondcode/install.sh
vim-prettier/install.sh
vim-shfmt/install.sh

Cleaning up a few things I've found along the way while preparing #718.
- `[ -n "$(command -v foo)"]` => `command -v foo > /dev/null`
- `[ -n "$(cat ./foo.txt)" ]` => `test -s ./foo.txt`
- `echo $(foo) | cut -d' ' -f2` => `foo | tr -s ' ' | cut -d' ' -f2`
The number and complexity of these changes were right in that middling number where I decided not to automate it, but I have triple checked each line of change to make sue the `-z` vs `-n` and `!` were all transitioned correctly.

style+lint: simplify `test`s to use exit code & file size rather than output/contents

---

_webi/template.sh
git-config-gpg/install.sh
gpg-pubkey/install.sh
gpg/install.sh
iterm2/install.sh
macos/install.sh
myip/install.sh
vps-utils/install.sh

Simplifying the `webi_download` function and using it consintently.
- separates error check
- easier to grok
- easier to `grep -A 2`

style+lint: `webi_download` should always use 2-3 args

---

_webi/template.ps1
xcaddy/install.ps1

While I was doing #718 I discovered that:
- xcaddy should not rely on a specific `go` path
- PowerShell should also reserve red text for errors

minor cleanup and fixes (discovered during #718)

---

_webi/template.sh

Those backslashes... they'll getcha!
This only affected error messages on BusyBox sed
(and the backslash for the escape you thought you needed, but didn't, of course)

fix(busybox): remove extraneous regex escape

---

_webi/bootstrap.sh
_webi/normalize.js
_webi/releases.js
_webi/serve-installer.js
_webi/template.sh
_webi/test.js
_webi/transform-releases.js
_webi/ua-detect.js
_webi/webi-pwsh.ps1
atomicparsley/releases.js
cmake/install.ps1
cmake/releases.js
node/releases.js

re #728 
This change ended up being larger in scope than I thought.
It's definitely more of a "manually test" than "just look at the code".
```sh
mv ~/.local/ ~/.local.1.old/
curl -sS https://next.webinstall.dev/cmake | sh
curl -sS https://next.webinstall.dev/node | sh
curl -sS https://next.webinstall.dev/atomicparsley | sh
curl -sS https://next.webinstall.dev/bat | sh
curl -sS https://next.webinstall.dev/jq | sh
curl -sS https://next.webinstall.dev/yq | sh
curl -sS https://next.webinstall.dev/ffmpeg | sh
source ~/.config/envman/PATH.env
node --version
AtomicParsley --version
bat -V
jq -V
yq -V
ffmpeg -version
```
```sh
mv ~/.local/ ~/.local.2.old/
curl -sS https://next.webinstall.dev/ | sh
export WEBI_HOST='https://next.webinstall.dev'
webi cmake
webi node atomicparsley bat jq yq ffmpeg …
```

feat+fix: explicit libc detection for musl, gnu, libc/none/static

---

_webi/releases.js
iterm2-utils/install.sh

Oops! A commit with the new filenames was pulled in by mistake!
This undoes that, which shouldn't come until #736 
Live in `hotfix`.

fix: don't switch template file name yet

---

_webi/curl-pipe-bootstrap.tpl.sh
archiver/install.ps1
git-gpg-init/install.ps1
gpg-pubkey/install.ps1
ripgrep/install.ps1
trippy/install.ps1
webi/webi-pwsh.ps1
zig.vim/install.ps1
ziglang/install.ps1
zoxide/install.ps1

Missing `-A MS` and `.ps1` for bootstrapping the os detection.
This part of a batch:

Fix curl to support windows aliases in dev

---

bat/install.ps1
bat/install.sh
curlie/install.ps1
curlie/install.sh
deno/install.sh
fd/install.ps1
fzf/install.ps1
jq/install.ps1
webi/webi-pwsh.ps1

Long ago I was testing something (I think) or for whatever reason I chose to use the name `.local\xbin`. That got copied and pasted in multiple places, which I don't think is what I intended.
And to this day, those things install in the wrong place.
This fixes that.
The fix will cause bug #747, but it's not workflow breaking, I think it's worth it for the future.

1.5 fix old typo xbin => bin

---

_webi/install-package.tpl.ps1
gpg-pubkey/install.ps1
myip/install.ps1
ssh-pubkey/install.ps1
webi/webi-pwsh.ps1

2. fix(windows): install scripts without PATH conflits between .bat and .ps1

---

_webi/install-package.tpl.ps1
ssh-authorize/README.md
ssh-authorize/install.ps1
ssh-authorize/ssh-authorize.ps1
webi/webi-pwsh.ps1

So. Much. Work.
But it works! On Windows!
Once this PR is pulled in:
```pwsh
curl.exe https://webi.ms/ssh-authorize | powershell
```
Just running the command with no arguments will correctly set the permissions:
```sh
ssh-authorize
```
Like this:
```sh
ssh-authorize https://github.com/johndoe.keys
```
Or this:
```sh
ssh-authorize ./johndoe.pub
```
It adds them to both of
- `$HOME\.ssh\authorized_keys`
- `${Env:ProgramData}\ssh\administrators_authorized_keys`
And uses `icacls.exe` to properly shift the permissions around so that `sshd` will run without complaining (and without disabling authorized keys).
This DOES NOT require `Repair-AuthorizedKeyPermission` from `OpenSSHUtils`, but if you'd like to see how it's done we have our own `Repair-UserAuthorizedKeyPermission` and …

3. feat(ssh-authorize): powershell edition for Windows

---

_webi/install-package.tpl.ps1
_webi/normalize.js
_webi/transform-releases.js
_webi/ua-detect.js
flutter/releases.js
gitea/install.ps1
webi/webi-pwsh.ps1
zig/releases.js

In prep for #756 
Critical fixes:
- classify `arm32` as `armv7`
- classify `arm` as `armv6` (though armv7 would do)
- use `-L` with curl in PowerShell because some GitHub downloads use redirects
Important fixes:
- use zig version rather than `master` for nightlies
- install `git` to install `gitea` on Windows
Included some chores as well
- `chmod a+x ./webi/webi.sh`
- show machine info in the welcome message in PowerShell

Hotfix: various minor updates already in prod

---

pwsh/install.sh

`ln -s ~/foo/ ~/bar/` won't work.
Gotta be `ln -s ~/foo/ ~/bar`. That's important.

fix(pwsh): '$pkg_dst' is a link, not a directory

---

flutter/releases.js

Found the release URLs doing a devtools inspect on the releases site:
https://docs.flutter.dev/release/archive?tab=windows
Thankfully that worked... for now.

Fix flutter release URLs

---

iterm2/install.sh

Checks the version in `/Applications/iTerm.app/Contents/Info.plist` before updating (iff `/Applications/iTerm.app/` exists).
`grep -A <n>` is pure magic! I wish I had known about this _YEARS_ ago!
```sh
grep -A 2 CFBundleShortVersionString \
/Applications/iTerm.app/Contents/Info.plist |
tr '<> \t' '\n' |
grep -E '\d\.\d\.\d'
```

fix(iterm2): don't update to the same version

---

ssh-adduser/ssh-adduser

Needs `${SSH_ADDUSER_AUTO:-}` when used standalone.

fix(ssh-adduser): check if SSH_ADDUSER_AUTO is set

---

cmake/releases.js
dashcore/releases.js
fd/releases.js
flutter/releases.js
go/releases.js
jq/releases.js
kubectx/releases.js
kubens/releases.js
terraform/releases.js
yq/releases.js

While working on #756 I discovered
- erroneous releases that cannot be matched generically
- some version numbers that don't match the file path
This updates those release files to produce clean outputs.

fix+lint release targets

---

chromedriver/install.sh
chromedriver/releases.js

We've been using an outdated release URL that's missing over a year of releases.
The new one is json, so it's much simpler.
This is a complete replacement and it passes the linter being built in #756. \
(in fact, that's why this issue was discovered)
```sh
curl https://next.webinstall.dev/chromedriver | sh
chromedriver --version
```

fix!(chromedriver): rewrite for latest releases URL

---

_webi/curl-pipe-bootstrap.tpl.sh
_webi/install-package.tpl.ps1
ssh-authorize/ssh-authorize.ps1
webi/webi-pwsh.ps1

Deployed to `hotfix`.
Re: #767 #769 
Improved error handling causes errors 🤷‍♂️. Reverted `--fail-with-body` (which is only a few years old) to `-f` (which works on old and enterprise-y systems).

fix: revert curl --fail-with-body to --fail

---

_webi/curl-pipe-bootstrap.tpl.sh
_webi/install-package.tpl.sh
_webi/releases.js
_webi/serve-installer.js
node/install.sh
vcruntime/install.sh
webi/webi.sh

`webi`, the command, has grown too big to be embedded any longer.
Plus, once we move it out, we may be able to drastically simplify the installer template as well. We shall see.

refactor `curl-pipe-bootstrap.tpl.sh` and `install-package.tpl.sh`

---

pwsh/releases.js

- PowerShell `-fxdependent` requires the c# runtime
- PowerShell musl actually requires musl libs

fix(pwsh): correctly classify musl, ignore c# builds

---

_webi/curl-pipe-bootstrap.tpl.sh
_webi/package-install.tpl.sh
webi/webi.sh

Failing on Alpine / Busybox wget due to `--show-progress`.
I discovered this since fixing TTY support in #736 while working on and testing #768
```sh
wget https://next.webinstall.dev/webi-essential -O - | sh
```
- prefer `curl` over `wget` (with `-#`, curl is just better)
- limit `wget` options on busybox
- no `-c` because it gives confusing errors when the file is downloaded (i.e. `https://example.com`)
- no `--show-progress` because it's not supported at all
- drop unused `WEBI_WGET` (to avoid furute confusion over something that does nothing)
Originally I preferred `wget` for `-c` to resume downloads (and maybe the nicer default progress bar), but in reality downloads rarely fail, and `curl -#` is better than `--progres=dot` for non-ttys.
Beyond that minimal Ubuntus and Alpine ship …

fix(busybox): wget on busybox

---

_webi/package-install.tpl.sh
webi-essentials/install.sh

Changed load.sh so that it will load only once.
On fresh debian and ubuntu systems, I have .profile calling .bashrc.
I like it that webi installs the load.sh source-calling in both, but I'd like it to load only once.
Added a 'singleton flag' of sorts to prevent load.sh from loading more than once in a session.

Only call load.sh once, even when .bashrc sources .profile

---

webi/webi.sh

There have been significant changes since b1d7df19:
https://github.com/webinstall/webi-installers/compare/b1d7df19...main?expand=1#diff-394881dbd4ce87350748996136104628b890fb4b02139e5d6d89b5d1208c3c11
I'm not quite ready to call this v1.3.0 - that will be once we bring in the same changes as in `_webi/curl-pipe-bootstrap.tpl.sh` and `_webi/package-install.tpl.ps1`.

chore: bump version to 1.2.7

---

_webi/package-install.tpl.sh
webi/webi.sh

`alias` and `export` syntax seem to be common among all shells, but function syntax is different between them.

fix: split non-portable function.env => function.sh, function.fish

---

_webi/curl-pipe-bootstrap.tpl.sh
_webi/package-install.tpl.sh
_webi/releases.js

Alpine (musl) and some BSDs don't always support `uname -o` (Operating System), which is required on Linux to distinguish between GNU and Bionic (Android).
This adds some feature detection for that.

fix OS detection when `uname -o` is not supported + typo fix in output

---

_webi/builds-cacher.js
package-lock.json
package.json

Amazingly, this didn't actually hard-break most (any?) downloads, but it sure looks like it would have.
For example:
```text
Extracting ~/Downloads/go/1.20/undefined
```
It worked, but...

fix(builds-cacher): fallback to setting build.name from build.download

---

webi/webi-pwsh.ps1

The fix from #799 allowed me to install webi successfully. However, after installation, running `webi` gives me the same error message related to the space in my username.
I found that modifying the `C:\Users\username with space\.local\bin\webi.bat` file to add `-File` and quotations around the path containing %USERPROFILE% allows me to run `webi` successfully one time. Running it once subsequently clobbers my changes to the webi.bat file and brings back the error.
I modified `webi-pwsh.ps1` to include these changes when it generates the webi.bat file.

fix(windows): use -File and quotations in webi.bat file to pass %USERPROFILE% as a single argument when it contains spaces

---

psscriptanalyzer/install.ps1
pwsh-essentials/install.ps1
sd/install.ps1
webi-essentials/install.sh
webi/webi-pwsh.ps1

Re #799 
In general variables don't need to be quoted in PowerShell - because variables are passed as objects.
However, when invoked with `&`, there's no consensus on how to properly quote them.
https://stackoverflow.com/questions/18537098/spaces-cause-split-in-path-with-powershell
However, in this particular case it looks like explicitly using `-File` works.

fix(windows): use -File to pass $HOME as a single argument when it contains spaces

---

vim-devicons/README.md

added the missing 'vim-' from the repository name

Fix vim-devicons homepage link

---

README.md

Updated README.md from `packages` to `webi-installers` to be in line with current project structure.
If you want to skip the PR process for this, I completely understand. This came up in issue #813.

docs(README.md): Update readme to reflect repo name change

---

pwsh/install.sh

Resolves #814 
Tried to test, but failed due to #813

Use full path to call pwsh, since it is not in the path yet

---

_common/gitea.js
_common/github.js
_common/githubish.js

Re: #850 
Gitea was receiving the (unprivileged) GitHub tokens. A recent update to Gitea caused it to error (due to the incorrect authentication).
This separates the GitHub auth from Gitea auth.

fix+sec: correctly scope GitHub tokens (don't send to Gitea)

---

_webi/package-install.tpl.sh

Work with `unxz` in Busybox, Alpine, Docker

fix(busybox): use -k instead of --keep

---

_common/githubish.js

Re #855, caused by #852.
Additionally
- `Authorization: Basic <base64(user:token)>` ALWAYS SUCCEEDS, even when the TOKEN IS INCORRECT \
(unless a rate-limit is hit)
- `Authorization: Bearer <token>` FAILS ON ERROR, as expected.
So that needs to be updated too.

fix(github-like): correct Authorization header

---

_example/README.md
_example/releases.js
cilium/README.md
cilium/install.ps1
cilium/install.sh
cilium/releases.js

Adding the command line tool to install and manage https://cilium.io
Based entirely on what the `kind` installer does.

feat: add cilium

---

koji/README.md
koji/releases.js

Repository has been transferred to https://github.com/cococonscious/koji

feat(koji): update releases and readme

---

vim-shell/install.sh

fix: set vim shell to 'sh' if 'bash' isn't in PATH

---

.gitignore
runzip/releases.js

runzip was added before the ` .getDistributables()`.
This updates `runzip` to use the correct function.
This also cleans up `.gitignore` to reduce clutter on `beta`.

fix(runzip): use .getDistributables()

---

git/README.md

TODO:
```sh
git config --global init.defaultBranch main
```

doc(git): update reasonable defaults

---

ollama/install.ps1
ollama/install.sh
ollama/releases.js

As per @jojobyte report of the Ollama CPU mismatch.
See also:
- https://github.com/webinstall/webi-build-classifier/pull/15
- https://github.com/webinstall/webi-installers/issues/879
- https://github.com/golang/go/issues/45453

fix(ollama): classify 'rocm' as its own cpu

---

ollama/install.ps1

In testing I created the download directory in order to save time on the 1.6gb download.
That turned out to be the wrong approach because the code wasn't creating the full download directory.

fix(windows+ollama): create download directory before downloading

---

_webi/package-install.tpl.ps1
vcruntime/install.ps1
webi/webi-pwsh.ps1

fixes #911
WMIC deprecated on Windows 11 and later versions of Windows 10 as per https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmic
This alternative works on both older and newer versions of Powershell, and outputs in a similar enough format that related code works with no additional changes.

fix - wmic deprecated

---

bun/README.md
caddy/README.md
fish/README.md
go/README.md
golang/README.md
node/README.md
postgres/README.md
ssh-adduser/ssh-adduser
ssh-pubkey/README.md
ssh-pubkey/ssh-pubkey

This PR addresses issue #854 by replacing all instances of the whoami command with id -u -n, aligning with the POSIX standard for guaranteed behavior across Unix-like systems.
**Changes Made:**
- Conducted a find-and-replace for whoami across relevant scripts and documentation files.
- Verified using grep that no remaining whoami instances exist within the repository.
This simple refactor improves cross-platform compatibility, following best practices as outlined in the issue description.

Refactor: Replace ```whoami``` with ```id -u -n``` in scripts for POSIX compliance (#854)

---

brew/brew-update-service-install
bun/README.md
caddy/README.md
dashcore-utils/README.md
dashcore-utils/dashd-hd-service-install
dashd/README.md
go/README.md
golang/README.md
node/README.md
pg/install.sh
postgres/README.md
postgres/install.sh
serviceman/README.md
serviceman/install.sh
serviceman/releases.js
syncthing/README.md

- update docs (`sudo` and `--path "$PATH"` are now automatic)
- update new homepage
- handle both install types
note: v0.9.1 wouldn't show up, but v0.9.0 would. There must be something funny about v0.x.1 versions.

feat(serviceman): update for v0.9

---

_webi/serve-installer.js

fixes #933 
Projects are marked as an `alias` if they're a symlink, or if `alias: ` is matched in the first 1k of of the `README.md`.
Excluding possible errors, the resolved projects are either `valid` (having a `releases.js`) or `selfhosted` (having an `install.sh` and local files committed to Webi, no remote releases).
Up to this point `alias` projects have simply been cached twice. However, `vim-mouse` is a symlink alias of `vim-gui`, which has no `releases.js` and was therefore failing module resolution (as it didn't match `selfhosted`).
This change resolves `alias` projects before checking if they're `valid` or `selfhosted`.

fix(api): 'alias' projects (symlinks) should be resolved before checking for 'selfhosted'

---

brew/brew-update-service-install
dashcore-utils/dashd-hd-service-install
syncthing/README.md

a few holdouts that were missed in #931

fix(serviceman) don't use sudo / env PATH=

---

shellcheck/README.md
shellcheck/install.sh

To finally close out https://github.com/webinstall/webi-installers/issues/335 (and keep the issues list to a single page).

doc(shellcheck): include common options, update usage and doc links

---

caddy/README.md
node/README.md
terramate/README.md
terramate/install.ps1
terramate/install.sh
terramate/releases.js

There's no easy way to install a specific version of terramate other than installing the latest through brew or downloading a specific release. So I thought why not add it this useful installer 😉

feat: Adding terramate support to webi

---

sass/releases.js

The term `arm` does not actually set a match - as it may ambiguously refer to any of `armv5`, `armv7l`, or `arm64`.
If no match is set, then the default for `musl` is to match `x86_64`.
As such, both `arm` (by default) and `x64` were matching `x86_64`.
These ambiguous and confusing cases must be matched manually.

fix(sass): manually match arches { arm: armv7, ia32: x86, x64: amd64 }

---

ssh-pubkey/ssh-pubkey
ssh-pubkey/ssh-pubkey.ps1

Generating sufficiently large RSA keys takes a really long time, and, as far as I can tell, ed25519 has been supported for a very long time. So I think it's time to switch the default.
Support was introduced in January of 2014, over 10 years ago.
On Ubuntu 20.04.1 LTS `ssh -V` shows `OpenSSH_8.2p1`.
Ubuntu 18.04.3 LTS `ssh -V` shows `OpenSSH_7.6p1`.
I don't have any running systems older than that.
Due to issues with various services not accepting RSA keys less than 3072 bits, the keys that previous issued a warning will now cause an ed25519 key to be generated, and show a prompt for how to manually generate a larger RSA key.
Re: https://github.com/webinstall/webi-installers/pull/841

ref(ssh-pubkey): switch to ed25519 as the primary algorithm

---

mariadb-server/README.md
mariadb-server/install.sh
mariadb/README.md
mariadb/install.sh
mariadb/releases.js
mariadbd/README.md
mariadbd/install.sh
mysql/README.md
mysql/install.sh
mysqld/README.md
mysqld/install.sh
serviceman/install.sh

For new development I'd almost always recommend Postgres, but for continuing to develop existing applications that used MySQL, MariaDB is more up-to-date, and convenient.
They provide default gnu/libc builds for Linux and Windows builds that are easy to install and configure.
The releases API seems to be manually generated (lots of inconsistencies), but it works for the LTS version (and hopefully will in the future).

feat: add MariaDB, via mariadb .com releases API

---

terramate/install.sh
terramate/releases.js

Sometime between testing and pushing to `main` we made a grave mistake - inverting the package test.
Fixes #957

fix(terramate): don't exclude package files

---

koji/README.md
koji/install.sh

The release process of koji has been updated a while ago, resulting in the binary not being nested in the archive anymore.
Fixes https://github.com/cococonscious/koji/issues/137

fix(koji): update binary path, docs
