ripgrep/releases.js
Kind of a start. Not sure if all the same os/arch mappings are there so I default a missing on to linux, atm.
=> Adding github release request mapper for ripgrep

caddy/releases.js, caddy/rg.bash
> Work in progress. Do not merge.
Working on a caddy installer.
=> WIP: caddy installer

_example/install.bat
Set URL, Parse CSV and breakdown into variables.
=> WIP: install.bat template, node example

README.md, brew/README.md, brew/install.sh, deno/install.ps1, sudo/README.md, sudo/install.ps1, sudo/install.sh
- https://github.com/webinstall/packages/issues/42 Sudo for Windows 10
- https://github.com/webinstall/packages/issues/43 local `brew`
- https://github.com/webinstall/packages/issues/48 deno for Windows 10
=> HOME-based brew, deno for Windows 10, README update

_npm/README.md, _npm/lib/exec.js, _npm/package-lock.json, _npm/package.json, _npm/scripts/install-webi.js, _webi/template.sh, bat/install.ps1, bat/install.sh, caddy/README.md, fd/README.md, fd/install.ps1, fd/install.sh, fd/releases.js, hexyl/README.md, hexyl/install.sh, hexyl/releases.js
- add log directive back to caddy docs
- add npm package (because... the world we live in)
- `~/.local/xbin/` -> `~/.local/opt/PKG_VER/bin/`
- add `hexyl`
- add `fd`
=> Update docs, add new packages, fix xbin => opt/x/bin

bat/install.sh, curlie/README.md, curlie/install.ps1, curlie/install.sh, curlie/releases.js, fd/install.sh, fzf/README.md, fzf/install.ps1, fzf/install.sh, fzf/releases.js, hexyl/README.md, hexyl/install.sh, rg/install.sh
`curlie` wraps `curl` to give it syntax highlighting like `httpie`
=> add curlie

postgres/README.md
=> bug fix issue 55

bat/README.md
Re: https://github.com/webinstall/packages/issues/58 https://github.com/webinstall/packages/issues/60
=> move bat cat explanation from usage to alias

nerd-font/install.sh, nerd-fonts/install.sh, nerdfont/README.md, nerdfont/install.sh, nerdfonts/install.sh
Just another simple thing that I want an easier way to install on new systems (and necessary before adding `lsd`).
=> add nerdfont

_webi/template.sh
This is my first PR. Let me know if you have any feedback!
=> agregate the download source #63

_webi/template.sh
I have never coded in shell script, and I just saw that someone else already sent a pull request but I guess it can't hurt to submit a request! Feel free to contact me on slack, thanks!
=> attempted fix

rg/install.sh
prepping for (hopefully) the last big change to `template.sh`.
=> cleanup rg's install.sh

.github/ISSUE_TEMPLATE/new_installer.md
add `.github/ISSUE_TEMPLATE/new_installer.md`
=> add git issue template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/new_installer.md
=> add bug report template (and fix typo)

_webi/test.js
I've correctly formatted the code and avoided any duplication of lines.
=> exe added to format array

comrak/install.ps1, git/install.ps1, golang/install.ps1, lsd/install.ps1, nerdfont/install.ps1, rg/install.ps1, ssh-utils/ssh-pubkey.ps1, vim-go/install.ps1, vim-sensible/install.ps1, vim-syntastic/install.ps1
Hope these would be the changes you want...in  #99
=> changes made

_webi/template.sh
=> resolve issue #100

caddy/install.ps1
Replaces https://github.com/webinstall/packages/pull/94 and Closes #93.
=> Add Caddy for Windows

wsl/README.md, wsl/install.ps1, wsl/install.sh, wsl2/README.md, wsl2/install-wsl2.ps1, wsl2/install.ps1, wsl2/install.sh
Re: #108 Compile the successes of https://github.com/microsoft/WSL/issues/5014 into a Just Works ™ script
Preview at https://beta.webinstall.dev/wsl2
=> add wsl and wsl2

wsl/README.md, wsl/install-wsl.ps1, wsl/install.ps1, wsl1/README.md, wsl1/install.ps1, wsl1/install.sh, wsl2/README.md, wsl2/install.ps1
Also make wsl2 the "canonical" WSL as per documentation.
=> fix WSL 2 kernel install

wsl/README.md
=> Finish the WSL Cheat Sheet

golang/install.sh, vim-go/README.md, vim-go/go.vim, vim-go/install.ps1, vim-go/install.sh, vim-prettier/README.md, vim-prettier/install.ps1, vim-prettier/install.sh, vim-prettier/prettier.vim
- add vim-prettier
- update vim-go and add sensible defaults
- update golang installer to install `goreturns`
Previewable at
- https://beta.webinstall.dev/vim-go
- https://beta.webinstall.dev/vim-prettier
=> add and update vim plugins with sensible defaults

arc/README.md, arc/install.ps1, arc/install.sh, arc/releases.js, archiver/install.ps1, archiver/install.sh
Supports just about everything (including zip, tar, xz, rar) except for 7z.
Preview at https://webinstall.dev/arc
=> Add arc for cross-platform (un)archiving

watchexec/README.md, watchexec/install.ps1, watchexec/install.sh, watchexec/releases.js
- Added `watchexec` 
- Added cheat sheets for `watchexec`
=> Added watchexec + cheat sheets

README.md, package.json
=> Housekeeping

goreleaser/README.md, goreleaser/install.ps1, goreleaser/install.sh, goreleaser/releases.js, package-lock.json
Please let me know what you think of the cheatsheet and if anything needs altering :smiley:
=> Adding Goreleaser

_webi/template.sh, flutter/install.sh, golang/install.sh, myip/myip.sh, vim-go/go.vim, vim-go/install.sh, watchexec/README.md
- updates how golang tooling is fetched
- make our own watchexec cheat sheet
=> update golang, vim-go, and watchexec

caddy/README.md, fish/README.md
- change fish color scheme
- system services with caddy
=> documentation updates

caddy/README.md, dotenv/README.md, dotenv/install.ps1, dotenv/install.sh, dotenv/releases.js
=> typo fix missing serviceman add

caddy/install.sh, dotenv/README.md, dotenv/install.sh, gitdeploy/README.md, gitdeploy/install.ps1, gitdeploy/install.sh, gitdeploy/releases.js
- add gitdeploy
- also some minor cleanup in comments and docs for caddy and dotenv
=> Add gitdeploy

dotenv/releases.js, gitdeploy/releases.js, golang/install.sh, keypairs/README.md, keypairs/install.ps1, keypairs/install.sh, keypairs/releases.js, vim-go/install.sh
adds cross-platform key generation, signing, and verification
Preview at https://beta.webinstall.dev/keypairs
=> add keypairs

_webi/normalize.js, pandoc/README.md, pandoc/install.ps1, pandoc/install.sh, pandoc/releases.js
As the Issue #74 mentions, I have added the pandoc installer
=> Added pandoc installer

dotenv-linter/README.md, dotenv-linter/install.ps1, dotenv-linter/install.sh, dotenv-linter/releases.js
For the README, I just copied the [dotenv-linter usage guide](https://dotenv-linter.github.io/#/usage) as it was fairly short.
Please let me know if I missed anything!
=> Add dotenv-linter (Closes #155)

serviceman/README.md, serviceman/install.ps1, serviceman/install.sh, serviceman/releases.js
Just moving serviceman to Github Releases for easier management.
=> move serviceman to github releases

arc/install.sh, gprox/README.md, gprox/install.ps1, gprox/install.sh, gprox/releases.js, iterm2/README.md, syncthing/README.md, syncthing/install.ps1, syncthing/install.sh, syncthing/releases.js
Hoping to leverage webi to install a simple local ssl proxy I wrote. Nothing too wild. I do need to double check with someone on Windows that the Powershell script works ok. Haven't done that just yet.
=> adding creedasaurus/gprox

arc/install.sh, gprox/README.md, gprox/install.ps1, gprox/install.sh, gprox/releases.js, iterm2/README.md, syncthing/README.md, syncthing/install.ps1, syncthing/install.sh, syncthing/releases.js
See the list of commits. The comments are fairly descriptive.
=> misc updates

kubectx/README.md, kubectx/install.ps1, kubectx/install.sh, kubectx/releases.js
See https://github.com/ahmetb/kubectx
Implements issue #173
Collaborative work of Nico Kerschbaumer and me
=> Added kubectx installer

shfmt/README.md, shfmt/install.ps1, shfmt/install.sh, shfmt/releases.js
Created installer for shfmt as mentioned in #105.
=> Added shfmt

kubens/README.md, kubens/install.ps1, kubens/install.sh, kubens/releases.js
Separate kubens installer  which is part of the kubectx repository as mentioned in #175
=> added kubens installer

shfmt/README.md
Changes made based on feedback given on #174
=> Updated README for shfmt

k9s/README.md
Added reference to K9s repo and information that certain k9s documentation sections are copied to the webi readme.
=> Updated readme for k9s

_example/README.md, _example/install.sh, chromedriver/README.md, chromedriver/install.ps1, chromedriver/install.sh, chromedriver/releases.js, pyenv/README.md, pyenv/install.sh
=> Added pyenv 

_example/README.md, chromedriver/README.md, chromedriver/install.ps1, chromedriver/install.sh, chromedriver/releases.js
Adds chromedriver installer for MacOS (including Apple Silicon / M1), Linux, and Windows.
=> add ChromeDriver

_webi/normalize.js, caddy/README.md, keypairs/install.sh, keypairs/releases.js, lf/install.sh, lf/releases.js, mutagen/README.md, mutagen/install.ps1, mutagen/install.sh, mutagen/releases.js, rclone/README.md, rclone/install.ps1, rclone/install.sh, rclone/releases.js
#167 
I have tested the bash script and it works perfectly. I am not sure about the PowerShell version as I was not able to test it. 
The cheat sheet looks a little too elaborate but I think these commands will be necessary for someone who hasn't used the tool before.
=> Add mutagen

shellcheck/README.md, shellcheck/install.ps1, shellcheck/install.sh, shellcheck/releases.js
Reference issue #211 
WIP
install.ps1
install.sh
readme
Working
releases.js
=> WIP:Shellcheck

brew/install.sh, git/install.sh, goreleaser/README.md
This resolves issue [issue #176 ](https://github.com/webinstall/webi-installers/issues/176)
=> Resolve missing 'v' in version string in readme

_webi/bootstrap.sh, _webi/releases.js, _webi/template.sh, webi/install.sh
- show welcome message (with contact info) BEFORE error checks
- follow best practices as recommended by shellcheck
- fix errors identified by shellcheck
=> welcome earlier, fix lint warnings and real errors

bat/install.ps1
This fix updates the path for the install file.
Closes #222
=> bugfix: update path for install file

ssh-utils/ssh-adduser.sh
- check at least one key in `~/.ssh/authorized_keys` (i.e. `/root/.ssh/authorized_keys`) before starting
- fix insecure `PasswordAuthentication yes` in `/etc/ssh/sshd_config`
- ensure that `/home/app/.ssh/authorized_keys` has the correct permissions
=> ssh-adduser: fix permissions & fix systems with ssh password vuln

zoxide/README.md, zoxide/install.ps1, zoxide/install.sh, zoxide/releases.js
Hey, I just discovered webi and I love how easy it is to use!
I've created an installer for [zoxide](https://github.com/ajeetdsouza/zoxide), a cross-shell autojump tool written in Rust.
=> Add zoxide installer

kind/README.md
Add more content to kind cheatsheet for #196
=> Additions to kind cheatsheet

kind/README.md, kind/install.ps1, kind/install.sh, kind/releases.js
#196 
Bash script: Tested and working
Powershell script: Not tested
Cheatsheet: Can be improved
=> Added kind

README.md, node/README.md, pyenv/README.md, rust.vim, vim-leader/install.sh, vim-rust/README.md, vim-rust/install.ps1, vim-rust/install.sh, vim-rust/rust.vim, zoxide/README.md, zoxide/install.sh
As per https://github.com/webinstall/webi-installers/issues/269
=> feature: add vim-rust

zoxide/install.sh
Fixes https://github.com/webinstall/webi-installers/issues/310, closes https://github.com/ajeetdsouza/zoxide/issues/296.
=> Fix zoxide installer

gh/README.md
I've added cheat cheet for 'gh' command-line. Cheat sheet describes the utility of 'gh' command-line.
=> add:'gh' cheatsheet

_webi/template.sh, fish/install.sh, gh/README.md, gh/install.ps1, gh/install.sh, gh/releases.js, git-gpg-init/README.md, git-gpg-init/git-gpg-init.sh, git-gpg-init/install.sh, gnupg/install.sh, gpg-pubkey/README.md, gpg-pubkey/gpg-pubkey-id.ps1, gpg-pubkey/gpg-pubkey-id.sh, gpg-pubkey/gpg-pubkey.ps1, gpg-pubkey/gpg-pubkey.sh, gpg-pubkey/install.ps1, gpg-pubkey/install.sh, gpg/README.md, gpg/install.ps1, gpg/install.sh, gpg/releases.js, iterm2/install.sh, macos/releases.js, ssh-pubkey/install.sh, ssh-utils/ssh-adduser.sh, ssh-utils/ssh-pubkey.sh
=> Add gh installer

iterm-utils/install.sh, iterm2-utils/README.md, iterm2-utils/install.sh, iterm2/install.sh, postgres/install.sh, rustlang/install.sh, vim-sensible/install.ps1, vim-sensible/install.sh
Fixes https://github.com/webinstall/webi-installers/issues/306
=> bugfix: make sure that ~/Applications exists

_webi/bootstrap.sh, _webi/template.sh
Re https://github.com/webinstall/webi-installers/issues/287
You can see what this looks like on beta:
```bash
export WEBI_HOST=https://beta.webinstall.dev
webi rg
```
=> feature: spam for stars plzkthx

setcap-netbind/README.md, setcap-netbind/install.sh, setcap-netbind/setcap-netbind.sh, vim-essentials/README.md, vim-essentials/install.sh, vps-utils/README.md, vps-utils/cap-net-bind.sh
=> [wip] setcap-netbind and vps-essentials

setcap-netbind/README.md, setcap-netbind/install.sh, setcap-netbind/setcap-netbind.sh, vim-essentials/README.md, vim-essentials/install.sh, vps-utils/README.md, vps-utils/cap-net-bind.sh
=> docs: recommend vim-rust (and devicons too)

rg/install.sh
According to  [Internal] Cleanup & Style #325 
I added shebang, function name and brought set -e and set -u outside of the function.
=> added shebang, set outside of function, added function name

arc/install.sh, bat/install.sh, chromedriver/install.sh, comrak/install.sh, curlie/install.sh, dotenv-linter/install.sh, fd/install.sh, ffmpeg/install.sh, fzf/install.sh, goreleaser/install.sh, hexyl/install.sh, jq/install.sh, k9s/install.sh, kubectx/install.sh, kubens/install.sh, lsd/install.sh, myip/install.sh, pandoc/install.sh, powershell/install.sh, sd/install.sh, shfmt/install.sh, ssh-utils/install.sh, sudo/install.sh, vps-addswap/install.sh, vps-utils/install.sh, watchexec/install.sh, xz/install.sh, yq/install.sh
Added shebang, set bash strict mode, create function where it was missing. This was done in an automated way, I checked all the files and it seems in order.
According to  [Internal] Cleanup & Style #325 
If something is not right, please let me know!
=> add shebang, set bash strict mode, create function

vim-shfmt/install.sh
Basically this:
```diff
- rm -rf plugins/start/shfmt.vim
+ rm -rf plugins/start/vim-shfmt
```
=> bugfix(vim-shfmt): fix package name

ripgrep/install.ps1
Making ripgrep installer an alias for rg
=> ripgrep / rg alias (see #221)

README.md, _webi/releases.js, python/README.md, python/install.sh, python2/README.md, python2/install.sh, python3/install.sh
https://beta.webinstall.dev/python
=> Add python

CONTRIBUTING.md
I just updated the comment as the command given was in an incorrect order.
=> docs updates: jshint (and contrib docs pulled in as well)

ots/README.md, ots/install.ps1, ots/install.sh, ots/releases.js, test/install.sh
otsgo is a simple CLI and API client for One-Time Secret written in Go.
Project: https://github.com/emdneto/otsgo
=> [Installer] - otsgo

rustlang/README.md, zig/README.md, zig/install.ps1, zig/install.sh, zig/releases.js, zig/zig-create-crossies.sh, ziglang/README.md, ziglang/install.ps1, ziglang/install.sh
Please let me know if this is not correct, as that would mean that I did something wrong!
=> docs(rustlang): Rust Hello World instructions

zig/README.md, zig/install.ps1, zig/install.sh, zig/releases.js, zig/zig-create-crossies.sh, ziglang/README.md, ziglang/install.ps1, ziglang/install.sh
Note: Rust cross-compile docs need some work.
Re: #427
=> feat: add ziglang

pyenv/install.sh
Added new install instructions for pyenv to the config.fish file.
This pull request resolves issue #423 .
=> Added new install instructions for pyenv on fish shell

caddy/README.md
Re: https://twitter.com/coolaj86/status/1535047881756790784
=> doc(caddy): add reverse_proxy + redirect

rustlang/install.sh
Hello!
I removed the default env loading into a shell config. I use for that a
`sd` and `pathman`.
If something I misunderstood please tell me what I did wrong.
Thank you,
y0rune
Re: #419
=> update rust installer with new PATHs

koji/install.sh
Ref: https://github.com/its-danny/koji
=> feat(koji): update installer and readme

go-essentials/README.md, go-essentials/install.ps1, go-essentials/install.sh, golang/README.md, golang/install.ps1, golang/install.sh
Prior instructions:
```console
go fmt ./...
> pattern ./...: directory prefix . does not contain main module or its selected dependencies
```
```console
go build .
> go: cannot find main module
...
```
- Need to use go install package@latest? directory change issue?
=> docs(golang): update 'hello world' build + run, fix windows install, etc

git-config-gpg/git-config-gpg.sh, git-config-gpg/install.sh, go-essentials/install.sh, golang/install.sh, gpg-pubkey/install.sh, jshint/install.sh, prettier/install.sh, vim-beyondcode/install.sh, vim-essentials/install.sh, vim-prettier/install.sh, vim-shfmt/install.sh
fixes https://github.com/webinstall/webi-installers/issues/388, and other related bugs
=> hotfix: always use full PATH to 'webi' command

arc/install.sh, awless/install.sh, caddy/install.sh, dashmsg/install.sh, deno/install.sh, dotenv/install.sh, flutter/install.sh, gitdeploy/install.sh, gitea/install.sh, hugo/install.sh, keypairs/install.sh, postgres/install.sh, powershell/install.sh, rclone/install.sh, sclient/install.sh, serviceman/install.sh, syncthing/install.sh
Hello!
I done the issue https://github.com/webinstall/webi-installers/issues/466.
I have tested the all packages too ;) 
Please review my PR. I think it is simple :D
Thank you!
=> Removing a echo with command in the repo

_webi/template.sh, macos/install.sh, ssh-adduser/ssh-adduser.sh
Added corrections to the previous pull request to replace all the '=='  that were missed.
=> Replace '==' with '=' according to shellcheck SC3014 (added corrections)

vps-addswap/install.sh
Removes current use of EUID and UID in favour of id
Closes: #482
=> fix(vps-addswap): updates root check

gpg-pubkey/gpg-pubkey.sh
=> refactor!(posix): translate 'read -s' bashism (shellcheck SC3045)

_webi/template.sh, git-config-gpg/git-config-gpg.sh, gpg-pubkey/gpg-pubkey.sh
- `echo -n` with `printf`
- (would be `echo -e` with `printf` too, FYI)
fixes #479
=> refactor(posix): replace echo bashisms with printf (fixes #479, SC3037)

_webi/example_install_safe_copy.sh, brew/install.sh, git/install.sh, pyenv/install.sh
Removed wrapping around if blocks
=> Fixed all shellcheck warnings and style updates #500

_webi/bootstrap.sh, _webi/template.sh, vps-addswap/install.sh
Updated printf strings from variable interpolation to variables substitution, according to the schellcheck suggestions and formatted the code using shfmt.
=> Refactor to make sure printf format strings don't use variables and make sure variables are inside quotes.

_webi/bootstrap.sh, _webi/example_install_safe_copy.sh, _webi/template.sh, macos/install.sh, test/install.sh
=> refactor(sh): remove junk output redirects, and set strict

CONTRIBUTING.md, README.md, caddy/README.md, package.json, powershell/README.md
Todo: add https://gist.github.com/nicerobot/53cee11ee0abbdc997661e65b348f375
=> chore: update `fmt` rules and contributor guidelines

brew/install.sh, pyenv/install.sh, vps-addswap/install.sh
Fixes #506 
@coolaj86 I think the shfmt config is good in this one, if not do lemme know : )
=> lint(sh): ignore warnings about expansion in docstrings (fixes #506)

pyenv/install.sh, vim-leader/install.sh, vim-shell/install.sh
=> use output blocks for multi-command output redirect (SC2129) #511

fzf/releases.js
change repo from `fzf-bin` to `fzf`
=> fix(fzf) update release.js

pyenv/README.md, python/install.sh, python2/install.sh
Use more strict version checking as to not catch weird versions by mistake
=> fix(python): update version checks

caddy/README.md
Re: https://github.com/webinstall/webi-installers/issues/487
=> docs(caddy): update examples, simplify config

package-lock.json, package.json
See https://github.com/webinstall/webi-installers/issues/534
=> hotfix: update @root/request for hanging error bugfix

vim-leader/README.md
Updated VIM Leader cheatsheet - added missing word. 
-- Sorry @coolaj86 it bothered me for too long, had to submit
=> Missing word - VIM Leader Cheatsheet

bun/README.md, bun/install.sh, bun/releases.js
I started to add bun in the same way that `rustlang` was added (just use the official script)... but it's `bash` rather than `POSIX` and it doesn't have version control (yet).
So GitHub Releases for now. :)
https://beta.webinstall.dev/bun
=> feat: add bun

_common/github.js, aliasman/README.md, aliasman/install.sh, aliasman/releases.js
admittedly the second should have been its own PR, but...
=> hotfix: log GitHub API errors, add aliasman

_webi/bootstrap.sh, _webi/template.sh, archiver/install.sh, gnupg/install.sh, go-essentials/install.sh, go/install.sh, golang/install.sh, iterm-color-schemes/install.sh, iterm-themes/install.sh, iterm-utils/install.sh, iterm/install.sh, iterm2-color-schemes/install.sh, nerd-font/install.sh, postgresql/install.sh, pwsh/install.sh, python3/install.sh, ripgrep/install.sh, rust/install.sh, setcap-netbind/setcap-netbind.sh, ssh-setpass/ssh-setpass.sh, ziglang/install.sh
=> chore: update shfmt

golang/README.md, node/README.md, vim-ale/ale.vim, vim-essentials/README.md, vim-essentials/install.sh, vim-shell/README.md, vim-smartcase/README.md, vim-smartcase/install.sh, vim-smartcase/smartcase.vim, vim-spell/README.md
=> add vim-smartcase, fix latest vim-ale, various doc updates

bat/README.md, delta/README.md, fish/install.sh
(otherwise pathman detection goes sadways)
=> fix(fish): ensure the config file always exists

bat/README.md
Add files section for `bat` to README.md
=> doc(bat) add Files section

arc/README.md
Added files section for `arc`. 
I can put these all in one commit if you'd prefer. I don't know how many I'll get to though.
=> doc(arc) add Files section

ssh-adduser/ssh-adduser.sh
```sh
ssh-adduser <user> [keys-url]
```
=> feat(ssh-adduser): allow authorized_keys url

prettier/README.md, shellcheck/README.md, shfmt/README.md, vim-prettier/README.md, vim-shfmt/README.md
=> docs: update Files section for (vim-)prettier, shellcheck, and (vim-)shfmt

vim-prettier/prettier.vim
this doesn't feel like programming... it feels like rolling dice
=> fix(vim-prettier): add back explicit file extension detection

beyond-shell/README.md, beyond-shell/install.sh
a more full-proof installer that's also more clear as to what's installed or being installed
```sh
curl https://beta.webinstall.dev/beyond-shell | sh
```
```text
Thanks for using webi to install 'beyond-shell@stable' on 'Linux/5.19.0-23-generic/x86_64'.
Have a problem? Experience a bug? Please let us know:
https://github.com/webinstall/webi-installers/issues
Lovin' it? Say thanks with a Star on GitHub:
https://github.com/webinstall/webi-installers
Log will be written to ~/.local/share/beyond-code/var/
webi at ~/.local/bin/webi
[Info] PATH updates in ~/.config/envman/PATH.env
[Fixup] create ~/bin/
[Fixup] create ~/.vimrc
[Fixup] create ~/.config/envman/alias.env
[Fixup] Installing Node.js to ~/.local/opt/node/
[Fixup] Installing aliasman to ~/.local/bin/aliasman
[Fixup] Installing bat to …
```
=> feat: add beyond-shell (for Workshops)

sttr/README.md, sttr/install.ps1, sttr/install.sh, sttr/releases.js
sttr is a cross-platform, cli app to perform various operations on string.
Github repo: https://github.com/abhimanyu003/sttr
=> feat: add sttr

_webi/template.ps1, _webi/webi-pwsh.ps1, _webi/webi.bat, deno/install.ps1, git/install.ps1, golang/install.ps1, node/install.ps1, pathman/install.ps1, sass/install.ps1, sudo/install.ps1, webi/README.md, zig/install.ps1
At long last, https://github.com/webinstall/webi-installers/issues/428 has come to fruition (thanks in large part to #597 and #598).
> When it is broken, it is the right time to fix it. - Chinese Fortune Cookie I once had
=> ref!: replace pathman with PowerShell [Environment]::SetEnvironmentVariable

_webi/transform-releases.js, _webi/webi-pwsh.ps1
Waiting for your feedback, @HacDan. You better love me forever for this.
I want my $2.
=> fix(windows): detect Windows ARM64, with AMD64 fallback

vim-italics/README.md, vim-italics/install.sh, vim-italics/italics.vim, vim-italics/spell.vim
I have read the CLA Document and I hereby sign the CLA
=> feat: add vim-italics (re: #589)

ssh-adduser/install.sh, ssh-adduser/ssh-adduser.sh, ssh-harden/README.md, ssh-harden/ssh-harden.complex, ssh-prohibit-password/README.md, ssh-prohibit-password/install.sh, ssh-utils/README.md, ssh-utils/install.sh, sshd-prohibit-password/README.md, sshd-prohibit-password/install.sh, sshd-prohibit-password/sshd-prohibit-password
moving the prohibit password checks from ssh-adduser into their own utility
To-Do:
=> feat: add sshd-prohibit-password

ssh-authorize/README.md, ssh-authorize/install.sh, ssh-authorize/ssh-authorize, ssh-utils/README.md, ssh-utils/install.sh
As discussed in #272 
I've run various tests with good and bad files, urls, and existing and non-existing folder structure.
It's good. It's ready.
=> feat: add ssh-authorize

dashcore-utils/dash.example.conf
Making note of https://github.com/dashpay/dash/issues/5461
=> doc(dashcore): note zmq bind behavior

cmake/README.md, cmake/install.ps1, cmake/install.sh, cmake/releases.js, test/install.sh
Addon changes:
- Added share directory to install script to fix CMAKE_ROOT not found issue.
- Added a simple CPP Hello World program for CMake usage.
Caution:
- Need to test Powershell script.
=> feat(cmake): Added CMake package

lsd/README.md, lsd/releases.js, vim-ale/ale.vim
=> ref(lsd): enable musl builds, update docs

AtomicParsley, atomicparsley/README.md, atomicparsley/install.ps1, atomicparsley/install.sh, atomicparsley/releases.js
Adding this because `ffmpeg` can't seem to edit album art in MPEG-4 tags on Audiobook (.m4b) files.
=> feat: add atomicparsley

_webi/normalize.js, _webi/ua-detect.js, aliasman/releases.js, duckdns.sh/releases.js
=> fix(ppc64le): sort ppc64le BEFORE ppc64

.github/workflows/node.js.yml, .jshintignore, .prettierignore, .prettierrc.json, _common/gitea.js, _npm/lib/exec.js, _scripts/install-ci-deps, _webi/normalize.js, dashcore-utils/README.md, ffmpeg/README.md, iterm2/releases.js, nerdfont/README.md, package-lock.json, package.json, package.json.extra, sclient/README.md, sttr/README.md, vim-airline-themes/install.sh, zig/README.md, zig/releases.js
=> chore: cleanup and workflow actions

grype/README.md, grype/install.ps1, grype/install.sh, grype/releases.js
PR for Grype https://github.com/webinstall/webi-installers/issues/540
=> add grype + cheatsheet

xsv/README.md, xsv/install.ps1, xsv/install.sh, xsv/releases.js
=> added xsv installer

xsv/README.md
This MR aims to solve issue https://github.com/webinstall/webi-installers/issues/670
=> Fix missing | to command list

arc/README.md, awless/README.md, brew/README.md, caddy/README.md, comrak/README.md, curlie/README.md, dotenv-linter/README.md, dotenv/README.md, fd/README.md, ffmpeg/README.md, flutter/README.md, fzf/README.md
This PR includes changes for the following READMEs:
=> doc: Updating READMEs Files section #660

_webi/bootstrap.sh, _webi/template.sh
Fixes this [issue](https://github.com/webinstall/webi-installers/issues/668)
I changed all instances of `\e[31m` to `\e[33m`
=> style(template&bootstrap): Change red text to yellow

AtomicParsley, bat/README.md, bat/install.ps1
I did all the suggestions
#675
=> feat(bat): Add mscv update to bat installer

.vimrc, _scripts/pwsh-fmt, _scripts/pwsh-fmt.ps1, _scripts/pwsh-lint, _scripts/pwsh-lint.ps1
We're gonna lint the powershell files now too!
Re: #683
=> chore(pwsh): add tooling configs

node/README.md
https://github.com/webinstall/webi-installers/tree/coolaj86-node-serviceman/node
=> doc(node): add serviceman examples

caddy/README.md
https://github.com/webinstall/webi-installers/tree/doc-caddy/caddy
=> doc!(caddy): complete cheat sheet rewrite + extras

brew/brew-update-service-install
=> Add --workdir flag to brew updater

.github/workflows/node.js.yml, brew/brew-update-service-install, xcaddy/README.md, xcaddy/install.ps1, xcaddy/install.sh, xcaddy/releases.js
Since I generally don't use tools that aren't on Webi for more than a one-off... it's time to bring `xcaddy` into the fold!
Also: https://github.com/caddyserver/xcaddy/pull/159
=> Add `xcaddy`

_webi/bootstrap.sh, _webi/template.sh
This should fix #711 
It adds an if condition of
```sh
test -z "$WEBI_WELCOME"
```
to the install script and should only run if WEBI_WELCOME doesn't have a value
Should I add another (AND or OR) condition to make sure it `=true`?
P.S. - Also I'm having a hard time testing my code, I tried `WEBI_PKG=vim-essentials bash _webi/bootstrap.sh` but it only displays the love message once. Any recommendations?
=> Fix: Add if condition to welcome message

goreleaser/README.md, goreleaser/install.sh, sclient/README.md
GoReleaser
- `--skip-publish` => `--skip=publish`
- `--rm-dist` => `--clean`
- `Archives.replacements` => N/A
- add `wasm` and `freebsd`
sclient
- add `--alpn <protos>`
=> doc: update for goreleaser v1.x and sclient v1.5

ollama/README.md, ollama/install.ps1, ollama/install.sh, ollama/releases.js
The basics, untested because I don't know how
=> feat: add barebones ollama start

gh/README.md, git/README.md, gitdeploy/README.md, gitea/README.md, goreleaser/README.md, gprox/README.md, hexyl/README.md, jq/README.md, keypairs/README.md, kind/README.md, kubectx/README.md, kubens/README.md, mutagen/README.md, myip/README.md
Just missing some READMEs for MacOS packages.
=> doc: Update Files section of READMEs from g to m (#660)

pandoc/README.md, pathman/README.md, postgres/README.md, rustlang/README.md, sass/README.md, sclient/README.md, sd/README.md, serviceman/README.md, setcap-netbind/README.md, ssh-adduser/README.md, ssh-authorize/README.md, ssh-pubkey/README.md, ssh-setpass/README.md, ssh-utils/README.md, sshd-prohibit-password/README.md, sttr/README.md, syncthing/README.md
These are the modified list from the issue checklist:
=> doc: Update Files section of READMEs from p to s (#660) 

vim-ale/README.md, vim-beyondcode/README.md, vim-devicons/README.md, vim-go/README.md, vim-gui/README.md, vim-lastplace/README.md, vim-leader/README.md, vim-nerdtree/README.md, vim-rust/README.md, vim-sensible/README.md, vim-syntastic/README.md, vim-viminfo/README.md, vim-whitespace/README.md, vps-addswap/README.md, vps-utils/README.md, watchexec/README.md, webi/README.md, xz/README.md, yq/README.md, zoxide/README.md
=> doc: Update Files section of READMEs from t to z (#660)

_common/git-tag.js, vim-commentary/install.ps1, vim-commentary/install.sh, vim-zig/README.md, vim-zig/install.ps1, vim-zig/install.sh, vim-zig/releases.js, vim-zig/zig.vim, zig.vim/README.md, zig.vim/install.ps1, zig.vim/install.sh, zig.vim/releases.js
Re: #724 
- add `fetch` to update repos
- add `getTipInfo` for repos with 0 tags
- general cleanup (comments, names)
- add vim-zig as test repo
- fix vim-commentary (as per things noticed with vim-zig)
=> fix+feat Git Source Releases: fetch & use HEAD as fallback (or beta)

_webi/template.ps1, _webi/template.sh
This one snuck by for a long time.
I mean, it _usually_ worked.
=> fix(windows): use home directory, not current directory

tinygo/README.md, tinygo/install.ps1, tinygo/install.sh, tinygo/releases.js
I finally rebuilt `pathman` in a way that came out to a reasonable size.
And if I use a tool... it goes on Webi.
=> feat: add TinyGo

_webi/releases.js
This is just a whitespace change. No functional differences.
=> ref(api): use await to de-indent some async functions

_webi/curl-pipe-bootstrap.tpl.sh, _webi/serve-installer.js
Most of these are already in prod
This part of a batch:
=> hotfixes: various mostly one-line fixes

_webi/install-package.tpl.ps1, caddy/README.md, go-essentials/install.ps1, go/install.ps1, golang/install.ps1, tinygo/install.ps1, vim-commentary/install.ps1, vim-things.sh, vim-zig/install.ps1, xcaddy/install.ps1
=> 1. fix windows $Env:Path management (and other minor fixes)

powershell/README.md, powershell/install.ps1, powershell/install.sh, psscriptanalyzer/README.md, psscriptanalyzer/install.ps1, psscriptanalyzer/install.sh, pwsh-essentials/README.md, pwsh-essentials/install.ps1, pwsh-essentials/install.sh, pwsh-essentials/pwsh-fix.ps1, pwsh-essentials/pwsh-fmt.ps1, pwsh-essentials/pwsh-lint.ps1, pwsh-essentials/pwsh-run.bat, pwsh/install.ps1
Merry Christmas, @HacDan!
(taking a short bio break and then I'll go test this on Windows)
This part of a batch:
=> 4. Feat pwsh essentials

_webi/package-install.tpl.sh, webi-essentials/README.md, webi-essentials/install.ps1, webi-essentials/install.sh
Installs curl, git, tar, wget, xz, and zip on Mac, Linux, Alpine (Busybox), and Windows!
- macOS
- Linux
- Windows
For a later commit
- Shell integrations will be part of
- #742 \
(but we want to tell about them now so it's not a surprise)
TTY detection is now 😘👨‍🍳 perfect!
=> feat: add webi-essentials - ensures curl, zip, etc exist & do shell integrations

_common/git-tag.js, _webi/transform-releases.js
The GitHub source releases can be surprisingly slow, so we bump the timeout from 5s to 15s.
=> fix(releases): bump github timeout to 15s, fix file write race condition

sd/install.sh
this will work with the new and the old package structure
=> fix(sd): update for v1 package structure

flutter/releases.js, go/releases.js, goreleaser/releases.js, ollama/releases.js, shellcheck/releases.js, watchexec/releases.js, zoxide/releases.js
- lots of little things discovered while pursuing (and necessary for) #756
=> fix: various minor issues with installers, prep for 100.0% classification

_webi/builds-cacher-test.js, _webi/builds-cacher.js, _webi/builds.js
Also fixes typo `bc.getProjectsByType()`
=> fix(cache): use correct timestamps and checks

julia/README.md, julia/install.ps1, julia/install.sh, julia/releases.js
Re: https://github.com/webinstall/webi-installer-requests/issues/76
=> feat: add julia (programming language)

brew/brew-update-service-install, commandlinetools/README.md, commandlinetools/install.sh, pyenv/README.md, pyenv/install.sh, xcode-cli
This copies and adapts functions from webi-essentials to improve pyenv to request to install missing dependencies.
I've tested on Mac, Ubuntu, and Alpine.
=> feat: install pyenv OS deps

_webi/package-install.tpl.sh
=> fix: init ~/.config/envman/ during init phase (before pre-install)

_webi/builds-cacher.js
=> fix(classifier): log rather than throw on failed classification

_webi/builds-cacher.js, _webi/classify-one.js
This was used to find the issue with #890
=> ref: make it easier to debug classification of a specific package

runzip/README.md, runzip/install.ps1, runzip/install.sh, runzip/releases.js
I came across some `.rar` files today and, instead of using `brew` (my nemesis), I had Gippity list me compiled languages that have unrar libraries, give me some boilerplate, and then I fixed it up, tested it, and published it.
Violá! the world is now a slightly brighter place. 😄
=> feat: add runzip for unzipping rar files

jsconfig.json
gonna make sure the prettiers and jshints, etcs are up-to-date
=> chore: add tooling

_common/githubish.js, pg/README.md, pg/install.sh, pg/releases.js, postgres-client/README.md, postgres-client/install.sh, postgres/README.md, postgres/install.sh, postgres/releases.js, postgresql-client/README.md, postgresql-client/install.sh, postgresql/install.sh, psql/README.md, psql/install.sh, psql/releases.js
Re:
- https://github.com/webinstall/webi-installers/issues/823 (now pg 17+)
- https://github.com/webinstall/webi-installers/issues/298 (will add pg-register-service)
- https://github.com/webinstall/webi-installers/issues/260 (some of this will go to pg-essentials)
=> feat: add postgres 17

sqlc/README.md, sqlc/install.ps1, sqlc/install.sh, sqlc/releases.js
Adds `sqlc`.
This is ready for approval, but before pulling it in I will also:
=> feat: add sqlc

_common/github-source.js, bun/releases.js, package-lock.json, package.json
That has been sitting in `hotfix` for a while now. Apparently when @jojobyte reported it (via Discord) I just fixed it and forgot to PR.
=> fix(bun): separate hard musl from libc (and some doc fixes)

node/README.md, node/install.sh
Re: https://github.com/webinstall/webi-installers/issues/775
=> feat(node): ask to install libstdc++
